---
title: "P8105 Homework 5"
author: "Grace Liu"
date: "11/8/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(purrr)
```

## Problem 1

```{r}
dataframe = 
  list.files("./data", pattern = "*.csv", full.names = TRUE) %>% 
  map(read_csv)

for (i in 1:20) {
  if (i <11) {
   dataframe[[i]] = dataframe[[i]] %>% 
     mutate(arm = "Control", study_id = i)
   }
  if (i >10) {
    dataframe[[i]] = dataframe[[i]] %>% 
      mutate(arm = "Experiment", study_id = i-10)
    }
}

participant_data =
  dataframe %>% 
  reduce(rbind) %>% 
  gather(key = week, value = observation, week_1:week_8) %>% 
  separate(week, into = c("remove", "week"), sep = "_") %>% 
  janitor::clean_names() %>% 
  select(arm, study_id, week, observation)
```

```{r}
participant_data %>% 
  ggplot(mapping = aes(x = week, y = weekly_total)) + 
    scale_y_continuous(labels = scales::comma) +
    geom_line(aes(color = "Weekly activity count totals")) +
        labs(x = "Week", y = "Total activity counts", 
         title = "Total activity counts, by week",
         subtitle = "(with locally-weighted smooth curve)",
         caption = "Figure 2") +
  scale_color_manual(name = "", values = c("Weekly activity count totals" = "lightsteelblue")) +
    theme(legend.position = "bottom")
```

